# 2 - Build OpenSSL docker build environement
name: CD 20 Build OpenSSL Docker Build Environement 
   
on:   
  workflow_run:
    workflows: [CD 10 OpenSSL Release Check]
    types:
      - completed

jobs:
  buildvars:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      : ${{ steps.IMPORT_BUILDVARS.outputs.DOCKER_IMAGE_VERSION }}
      BUILDENV_VERSION: ${{ steps.IMPORT_BUILDVARS.outputs.BUILDENV_VERSION }}
      OPENSSL_VERSION: ${{ steps.IMPORT_BUILDVARS.outputs.OPENSSL_VERSION }}
      BUILD_DATETIME: ${{ steps.IMPORT_BUILDVARS.outputs.BUILD_DATETIME }}
    
    steps:             
    - name: Checkout source
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    
    - name: Import build variables from buildvars file
      id: IMPORT_BUILDVARS
      run: |
        cat buildvars | grep BUILDENV_VERSION >> $GITHUB_OUTPUT
        cat buildvars | grep BUILD_DATETIME >> $GITHUB_OUTPUT
        cat buildvars | grep OPENSSL_VERSION >> $GITHUB_OUTPUT
    
  build_openssl: 
    runs-on: ubuntu-latest
    needs: buildvars
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKERHUB_SLUG: "megavolts/unbound"
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            BUILD_DATETIME=${{ needs.buildvars.outputs.BUILD_DATETIME }}  
            BUILDENV_VERSION=${{ needs.buildvars.outputs.DOCKER_IMAGE_VERSION }}
            OPENSSL_VERSION=${{ needs.buildvars.outputs.OPENSSL_VERSION }}
          file: ./openssl/release.Dockerfile   
          push: ${{ github.event_name != 'pull_request' }}
          sbom: ${{ github.event_name != 'pull_request' }}
          provenance: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:${{ needs.buildvars.outputs.DOCKER_IMAGE_VERSION }}   
            ${{ env.DOCKERHUB_SLUG }}:latest
    